-- =============================================================================
-- The presence heartbeat.
--
-- NOT EXECUTED BY THE DEPLOY PIPELINE. Prisma runs `migration.sql` in this
-- directory; this file is the hand-applied runbook, for a database that has not
-- received the change yet.
--
-- The dashboard writes `is_online` and `last_seen_at` on the signed-in user's own
-- `profiles` row, straight from the browser to PostgREST. That is the only write
-- the browser makes to any locked table.
--
-- The lock migration granted exactly that and nothing more:
--
--     CREATE POLICY "profiles_update_own" ON public.profiles
--       FOR UPDATE TO authenticated
--       USING (id = auth.uid()) WITH CHECK (id = auth.uid());
--
--     REVOKE ALL ON public.profiles FROM anon, authenticated;
--     GRANT UPDATE (is_online, last_seen_at) ON public.profiles TO authenticated;
--
-- A Postgres UPDATE policy is evaluated by reading the row it is deciding about,
-- and this one qualifies on the `id` column. `REVOKE ALL` left `authenticated`
-- unable to read `id`, so the policy could not be evaluated and every presence
-- write was refused: `PATCH /rest/v1/profiles` 403, silently, with no user ever
-- marked online and "STAFF ON DUTY" reading 0.
--
-- The grant is column-scoped to `id` on purpose. That UUID is `auth.uid()`, the
-- subject of the caller's own token, so it exposes nothing about any other row
-- and cannot enumerate. It does not reopen the breach the lock closed - the
-- containment rested on there being no anon/authenticated read path into the
-- six tables, and one column of one row is not a read path. It must not be
-- widened to include `role`: a SELECT on `role` would let a STAFF read roles
-- platform-wide, and a broader UPDATE would let them write their own role to
-- OWNER and satisfy every @Roles() check.
--
-- Do NOT follow the Postgres suggestion to add table grants back. On a 42501
-- Postgres emits a generic `HINT: Grant SELECT ... TO anon`. That hint is
-- boilerplate, is not specific to this policy, and acting on it would re-create
-- the breach the lock closed. RLS would still deny, but the only remaining
-- barrier would be a single policy someone could later drop.
--
-- Rollback, if the heartbeat must be withdrawn:
--
--     REVOKE SELECT (id) ON public.profiles FROM authenticated;
--
-- Note the consequence: presence tracking stops working and every user reads
-- offline. That is the correct failure direction - denied, not permissive.
--
-- `migration.sql` beside this file is the guarded, idempotent version the deploy
-- pipeline executes. Run that instead where you can.
-- =============================================================================
