-- v2.0 Schema Baseline (Phase 7, Plan 1)
-- Generated by hand per PLAN.md T2 fallback: `prisma migrate diff --from-url` times out against the Supabase transaction pooler.
-- Contents: additive only â€” CREATE TYPE / CREATE TABLE / ALTER TABLE ADD COLUMN / CREATE INDEX / INSERT ... ON CONFLICT DO NOTHING.
-- No DROP, no ALTER COLUMN TYPE, no UPDATE/DELETE of existing rows, nothing touching profiles.
-- Idempotency: CREATE TYPE guarded via DO $$ duplicate_object, tables/columns/indexes use IF NOT EXISTS, seed uses ON CONFLICT DO NOTHING.

-- ------------------------------------------------------------
-- Enums
-- ------------------------------------------------------------
-- CreateEnum CustomerTier
DO $$ BEGIN
  CREATE TYPE "public"."CustomerTier" AS ENUM ('STANDARD', 'BRONZE', 'SILVER', 'GOLD', 'VIP');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- CreateEnum ApprovalStatus
DO $$ BEGIN
  CREATE TYPE "public"."ApprovalStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- CreateEnum ApprovalTargetType
DO $$ BEGIN
  CREATE TYPE "public"."ApprovalTargetType" AS ENUM ('APPRAISAL', 'REDEMPTION', 'LOAN_APPLICATION');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- CreateEnum SignatureType
DO $$ BEGIN
  CREATE TYPE "public"."SignatureType" AS ENUM ('CANVAS', 'TYPED', 'UPLOADED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ------------------------------------------------------------
-- New tables
-- ------------------------------------------------------------

-- CreateTable Permission
CREATE TABLE IF NOT EXISTS "permissions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "group" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "permissions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex permissions_name_key
CREATE UNIQUE INDEX IF NOT EXISTS "permissions_name_key" ON "permissions"("name");

-- CreateTable RolePermission
CREATE TABLE IF NOT EXISTS "role_permissions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "role" TEXT NOT NULL,
    "permission_id" UUID NOT NULL,
    CONSTRAINT "role_permissions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex role_permissions_role_permission_id_key
CREATE UNIQUE INDEX IF NOT EXISTS "role_permissions_role_permission_id_key" ON "role_permissions"("role", "permission_id");

-- CreateIndex role_permissions_role_idx
CREATE INDEX IF NOT EXISTS "role_permissions_role_idx" ON "role_permissions"("role");

-- AddForeignKey role_permissions_permission_id_fkey
DO $$ BEGIN
  ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- CreateTable ApprovalRecord
CREATE TABLE IF NOT EXISTS "approval_records" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "pawnshop_id" UUID NOT NULL,
    "target_type" "public"."ApprovalTargetType" NOT NULL,
    "target_id" TEXT NOT NULL,
    "status" "public"."ApprovalStatus" NOT NULL DEFAULT 'PENDING',
    "amount" DOUBLE PRECISION,
    "requested_by_id" UUID NOT NULL,
    "decided_by_id" UUID,
    "decided_at" TIMESTAMP(3),
    "decision_comment" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "approval_records_pkey" PRIMARY KEY ("id")
);

-- CreateIndex approval_records_pawnshop_id_status_idx
CREATE INDEX IF NOT EXISTS "approval_records_pawnshop_id_status_idx" ON "approval_records"("pawnshop_id", "status");

-- CreateIndex approval_records_target_type_target_id_idx
CREATE INDEX IF NOT EXISTS "approval_records_target_type_target_id_idx" ON "approval_records"("target_type", "target_id");

-- AddForeignKey approval_records_pawnshop_id_fkey
DO $$ BEGIN
  ALTER TABLE "approval_records" ADD CONSTRAINT "approval_records_pawnshop_id_fkey" FOREIGN KEY ("pawnshop_id") REFERENCES "pawnshops"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- AddForeignKey approval_records_requested_by_id_fkey
DO $$ BEGIN
  ALTER TABLE "approval_records" ADD CONSTRAINT "approval_records_requested_by_id_fkey" FOREIGN KEY ("requested_by_id") REFERENCES "profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- AddForeignKey approval_records_decided_by_id_fkey
DO $$ BEGIN
  ALTER TABLE "approval_records" ADD CONSTRAINT "approval_records_decided_by_id_fkey" FOREIGN KEY ("decided_by_id") REFERENCES "profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- CreateTable CustomerKyc
CREATE TABLE IF NOT EXISTS "customer_kyc" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "customer_id" UUID NOT NULL,
    "pawnshop_id" UUID NOT NULL,
    "status" "public"."KycStatus" NOT NULL DEFAULT 'NOT_SUBMITTED',
    "full_name" TEXT NOT NULL,
    "contact_number" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "id_type" "public"."KycIdType" NOT NULL,
    "id_number" TEXT NOT NULL,
    "id_front_url" TEXT NOT NULL,
    "id_back_url" TEXT,
    "selfie_url" TEXT,
    "verification_data" JSONB,
    "reviewed_by" UUID,
    "reviewed_at" TIMESTAMP(3),
    "rejection_reason" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "customer_kyc_pkey" PRIMARY KEY ("id")
);

-- CreateIndex customer_kyc_customer_id_key
CREATE UNIQUE INDEX IF NOT EXISTS "customer_kyc_customer_id_key" ON "customer_kyc"("customer_id");

-- CreateIndex customer_kyc_pawnshop_id_status_idx
CREATE INDEX IF NOT EXISTS "customer_kyc_pawnshop_id_status_idx" ON "customer_kyc"("pawnshop_id", "status");

-- AddForeignKey customer_kyc_customer_id_fkey
DO $$ BEGIN
  ALTER TABLE "customer_kyc" ADD CONSTRAINT "customer_kyc_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- AddForeignKey customer_kyc_pawnshop_id_fkey
DO $$ BEGIN
  ALTER TABLE "customer_kyc" ADD CONSTRAINT "customer_kyc_pawnshop_id_fkey" FOREIGN KEY ("pawnshop_id") REFERENCES "pawnshops"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- CreateTable CustomerTierHistory
CREATE TABLE IF NOT EXISTS "customer_tier_history" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "customer_id" UUID NOT NULL,
    "from_tier" "public"."CustomerTier",
    "to_tier" "public"."CustomerTier" NOT NULL,
    "reason" TEXT NOT NULL,
    "changed_by_id" UUID,
    "changed_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "customer_tier_history_pkey" PRIMARY KEY ("id")
);

-- CreateIndex customer_tier_history_customer_id_changed_at_idx
CREATE INDEX IF NOT EXISTS "customer_tier_history_customer_id_changed_at_idx" ON "customer_tier_history"("customer_id", "changed_at");

-- AddForeignKey customer_tier_history_customer_id_fkey
DO $$ BEGIN
  ALTER TABLE "customer_tier_history" ADD CONSTRAINT "customer_tier_history_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ------------------------------------------------------------
-- Additive columns on existing tables
-- ------------------------------------------------------------

-- AlterTable Customer
ALTER TABLE "customer" ADD COLUMN IF NOT EXISTS "tier" "public"."CustomerTier" NOT NULL DEFAULT 'STANDARD';
ALTER TABLE "customer" ADD COLUMN IF NOT EXISTS "kyc_status" "public"."KycStatus" NOT NULL DEFAULT 'NOT_SUBMITTED';

-- AlterTable Receipt (optional Customer link, SET NULL on delete)
ALTER TABLE "receipts" ADD COLUMN IF NOT EXISTS "customer_id" UUID;

-- AddForeignKey receipts_customer_id_fkey
DO $$ BEGIN
  ALTER TABLE "receipts" ADD CONSTRAINT "receipts_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customer"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- CreateIndex receipts_customer_id_idx
CREATE INDEX IF NOT EXISTS "receipts_customer_id_idx" ON "receipts"("customer_id");

-- AlterTable PawnshopDocument (document acknowledgement)
ALTER TABLE "pawnshop_documents" ADD COLUMN IF NOT EXISTS "has_viewed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "pawnshop_documents" ADD COLUMN IF NOT EXISTS "viewed_at" TIMESTAMP(3);
ALTER TABLE "pawnshop_documents" ADD COLUMN IF NOT EXISTS "viewed_by" UUID;

-- AlterTable LoanContract (signature metadata)
ALTER TABLE "loan_contracts" ADD COLUMN IF NOT EXISTS "customer_signature_type" "public"."SignatureType" NOT NULL DEFAULT 'TYPED';
ALTER TABLE "loan_contracts" ADD COLUMN IF NOT EXISTS "customer_signature_image_url" TEXT;
ALTER TABLE "loan_contracts" ADD COLUMN IF NOT EXISTS "customer_signature_image_mime" TEXT;
ALTER TABLE "loan_contracts" ADD COLUMN IF NOT EXISTS "staff_signature_type" "public"."SignatureType" NOT NULL DEFAULT 'TYPED';
ALTER TABLE "loan_contracts" ADD COLUMN IF NOT EXISTS "staff_signature_image_url" TEXT;
ALTER TABLE "loan_contracts" ADD COLUMN IF NOT EXISTS "staff_signature_image_mime" TEXT;

-- ------------------------------------------------------------
-- Permission catalog seed (Phase 7 initial catalog, additive only)
-- ------------------------------------------------------------
INSERT INTO permissions (name, "group", description)
VALUES
  ('platform.manage', 'platform', NULL),
  ('tenant.manage', 'tenant', NULL),
  ('tenant.view_audit', 'tenant', NULL),
  ('tenant.manage_branches', 'tenant', NULL),
  ('user.manage_staff', 'user', NULL),
  ('pawn_ticket.create', 'pawn_ticket', NULL),
  ('pawn_ticket.view', 'pawn_ticket', NULL),
  ('pawn_ticket.submit_approval', 'pawn_ticket', NULL),
  ('pawn_ticket.approve', 'pawn_ticket', NULL),
  ('pawn_ticket.decline', 'pawn_ticket', NULL),
  ('pawn_ticket.appraise', 'pawn_ticket', NULL),
  ('pawn_ticket.redeem', 'pawn_ticket', NULL),
  ('pawn_ticket.send_to_auction', 'pawn_ticket', NULL),
  ('loan.create', 'loan', NULL),
  ('loan.manage', 'loan', NULL),
  ('loan.collect', 'loan', NULL),
  ('auction.manage', 'auction', NULL),
  ('auction.settle', 'auction', NULL),
  ('auction.manual_settle', 'auction', NULL),
  ('inventory.manage', 'inventory', NULL),
  ('compliance.view', 'compliance', NULL),
  ('compliance.manage_documents', 'compliance', NULL),
  ('onboarding.review_documents', 'onboarding', NULL),
  ('onboarding.approve', 'onboarding', NULL),
  ('reports.view', 'reports', NULL),
  ('finance.manage', 'finance', NULL),
  ('approval.view_queue', 'approval', NULL),
  ('approval.approve_appraisal', 'approval', NULL),
  ('approval.approve_redemption', 'approval', NULL),
  ('kyc.view', 'kyc', NULL),
  ('kyc.verify', 'kyc', NULL),
  ('contract.sign', 'contract', NULL),
  ('contract.upload_signature', 'contract', NULL),
  ('customer.view_history', 'customer', NULL),
  ('customer.manage_tier', 'customer', NULL),
  ('payroll.manage', 'payroll', NULL),
  ('attendance.manage', 'attendance', NULL)
ON CONFLICT (name) DO NOTHING;

-- Role -> permission matrix (101 mappings; SUPER_ADMIN gets platform.manage only,
-- all other mappings granted by role; OWNER = full catalog minus platform/onboarding)
INSERT INTO role_permissions (role, permission_id)
SELECT v.role, p.id
FROM (VALUES
  ('SUPER_ADMIN','platform.manage'),
  ('OWNER','tenant.manage'),
  ('OWNER','tenant.view_audit'),
  ('OWNER','tenant.manage_branches'),
  ('OWNER','user.manage_staff'),
  ('OWNER','pawn_ticket.create'),
  ('OWNER','pawn_ticket.view'),
  ('OWNER','pawn_ticket.submit_approval'),
  ('OWNER','pawn_ticket.approve'),
  ('OWNER','pawn_ticket.decline'),
  ('OWNER','pawn_ticket.appraise'),
  ('OWNER','pawn_ticket.redeem'),
  ('OWNER','pawn_ticket.send_to_auction'),
  ('OWNER','loan.create'),
  ('OWNER','loan.manage'),
  ('OWNER','loan.collect'),
  ('OWNER','auction.manage'),
  ('OWNER','auction.settle'),
  ('OWNER','auction.manual_settle'),
  ('OWNER','inventory.manage'),
  ('OWNER','compliance.view'),
  ('OWNER','compliance.manage_documents'),
  ('OWNER','reports.view'),
  ('OWNER','finance.manage'),
  ('OWNER','approval.view_queue'),
  ('OWNER','approval.approve_appraisal'),
  ('OWNER','approval.approve_redemption'),
  ('OWNER','kyc.view'),
  ('OWNER','kyc.verify'),
  ('OWNER','contract.sign'),
  ('OWNER','contract.upload_signature'),
  ('OWNER','customer.view_history'),
  ('OWNER','customer.manage_tier'),
  ('OWNER','payroll.manage'),
  ('OWNER','attendance.manage'),
  ('ADMIN','tenant.view_audit'),
  ('ADMIN','auction.settle'),
  ('ADMIN','auction.manual_settle'),
  ('ADMIN','approval.view_queue'),
  ('ADMIN','approval.approve_appraisal'),
  ('ADMIN','approval.approve_redemption'),
  ('ADMIN','kyc.view'),
  ('ADMIN','kyc.verify'),
  ('MANAGER','tenant.manage_branches'),
  ('MANAGER','user.manage_staff'),
  ('MANAGER','pawn_ticket.create'),
  ('MANAGER','pawn_ticket.view'),
  ('MANAGER','pawn_ticket.submit_approval'),
  ('MANAGER','pawn_ticket.approve'),
  ('MANAGER','pawn_ticket.decline'),
  ('MANAGER','pawn_ticket.appraise'),
  ('MANAGER','pawn_ticket.redeem'),
  ('MANAGER','pawn_ticket.send_to_auction'),
  ('MANAGER','loan.create'),
  ('MANAGER','loan.manage'),
  ('MANAGER','loan.collect'),
  ('MANAGER','auction.settle'),
  ('MANAGER','inventory.manage'),
  ('MANAGER','reports.view'),
  ('MANAGER','finance.manage'),
  ('MANAGER','approval.view_queue'),
  ('MANAGER','contract.sign'),
  ('MANAGER','customer.manage_tier'),
  ('MANAGER','attendance.manage'),
  ('HR','payroll.manage'),
  ('HR','attendance.manage'),
  ('STAFF','pawn_ticket.create'),
  ('STAFF','pawn_ticket.view'),
  ('STAFF','pawn_ticket.submit_approval'),
  ('STAFF','loan.create'),
  ('STAFF','compliance.view'),
  ('STAFF','compliance.manage_documents'),
  ('STAFF','contract.sign'),
  ('STAFF','customer.view_history'),
  ('CASHIER_TELLER','pawn_ticket.create'),
  ('CASHIER_TELLER','pawn_ticket.view'),
  ('CASHIER_TELLER','pawn_ticket.submit_approval'),
  ('CASHIER_TELLER','pawn_ticket.redeem'),
  ('CASHIER_TELLER','loan.create'),
  ('CASHIER_TELLER','loan.collect'),
  ('CASHIER_TELLER','compliance.view'),
  ('CASHIER_TELLER','compliance.manage_documents'),
  ('CASHIER_TELLER','contract.sign'),
  ('CASHIER_TELLER','customer.view_history'),
  ('CASHIER_TELLER','approval.view_queue'),
  ('APPRAISER','pawn_ticket.create'),
  ('APPRAISER','pawn_ticket.view'),
  ('APPRAISER','pawn_ticket.submit_approval'),
  ('APPRAISER','pawn_ticket.appraise'),
  ('APPRAISER','loan.create'),
  ('APPRAISER','compliance.view'),
  ('APPRAISER','compliance.manage_documents'),
  ('APPRAISER','contract.sign'),
  ('APPRAISER','customer.view_history'),
  ('APPRAISER','approval.view_queue'),
  ('INVENTORY_CUSTODIAN','pawn_ticket.view'),
  ('INVENTORY_CUSTODIAN','inventory.manage'),
  ('AUDITOR','pawn_ticket.view'),
  ('AUDITOR','reports.view'),
  ('AUDITOR','tenant.view_audit'),
  ('AUDITOR','finance.manage')
) AS v(role, permission_name)
JOIN permissions p ON p.name = v.permission_name
ON CONFLICT (role, permission_id) DO NOTHING;
