import { Link } from 'react-router-dom';
import { ArrowLeft, ShieldCheck } from 'lucide-react';

type Section = {
  heading: string;
  body: string[];
};

type LegalDocument = {
  metaTitle: string;
  updated: string;
  intro: string;
  sections: Section[];
};

const DOCUMENTS: Record<string, LegalDocument> = {
  '/terms': {
    metaTitle: 'Terms of Service',
    updated: 'Last updated: September 10, 2026',
    intro:
      'These Terms of Service ("Terms") govern your access to and use of the PawnGold platform, including any of its dashboards, website, and related services. By creating an account or using PawnGold, you agree to these Terms.',
    sections: [
      {
        heading: '1. About PawnGold',
        body: [
          'PawnGold is an academic thesis and capstone project developed for demonstration and educational purposes. It is not a registered financial institution, money service business, or pawnshop operator.',
          'The PawnGold platform provides administrative software tools that pawnshop owners may use to manage loans, pawn tickets, inventory, staff, and related operations. The platform does not itself conduct lending, pawnbroking, or auction activities on behalf of any user.',
        ],
      },
      {
        heading: '2. Accounts and Registration',
        body: [
          'To use PawnGold, you must register an owner account using a valid email address and a secure password. You are responsible for safeguarding your login credentials and for all activity that occurs under your account.',
          'You must provide accurate, current, and complete information during registration and keep your information up to date.',
          'One owner account is associated with one pawnshop organization. You are responsible for managing the roles and permissions of all users you invite to your organization.',
        ],
      },
      {
        heading: '3. Free Trial and Paid Plans',
        body: [
          'New organizations may start a free trial for a limited period. At the end of the trial, continued use is subject to an active subscription plan.',
          'Paid plans are billed through a payment processor (PayMongo) and are subject to that processor\u2019s terms. You authorize the charges associated with the plan you select.',
          'Trial and plan details, including feature lists and limits, are described on the PawnGold website and are subject to change with notice where reasonably practicable.',
        ],
      },
      {
        heading: '4. Acceptable Use',
        body: [
          'You agree not to use PawnGold to violate any applicable Philippine law, including but not limited to the Data Privacy Act (RA 10173), the Consumer Act (RA 7394), the E-Commerce Act (RA 8792), the Cybercrime Prevention Act (RA 10175), and the Anti-Money Laundering Act (RA 9160, as amended).',
          'You must not attempt to access another organization\u2019s data, probe or test the security of the platform without authorization, or interfere with the normal operation of the service.',
          'You must not reverse engineer, decompile, or otherwise attempt to derive the source code of the platform.',
        ],
      },
      {
        heading: '5. Your Data and Responsibilities',
        body: [
          'You are the controller of the business and customer data you enter into the platform. You must have the legal authority to collect, process, and store such data, and you must comply with all applicable privacy laws when using PawnGold.',
          'You are responsible for the accuracy of the information you enter, including customer details, item appraisals, loan amounts, and transaction records.',
          'PawnGold provides audit trails and records to help you document transactions, but you remain responsible for maintaining your own records as required by law.',
        ],
      },
      {
        heading: '6. No Professional, Legal, or Financial Advice',
        body: [
          'PawnGold provides software tools and templates. It is not a substitute for professional legal, accounting, or financial advice.',
          'Contract templates, receipts, and documents generated by the platform are provided as a convenience and should be reviewed by a qualified professional before use in real-world transactions.',
          'Interest, penalty, and redemption computations are provided as calculated estimates based on the rates and terms configured in your organization and may require adjustment to comply with applicable regulations.',
        ],
      },
      {
        heading: '7. Intellectual Property',
        body: [
          'The PawnGold platform, including its design, branding, text, graphics, and software, is protected by intellectual property laws. Except as explicitly permitted, you may not copy, modify, or redistribute any part of the platform.',
          'By submitting a review or feedback, you grant PawnGold a non-exclusive, royalty-free license to display the review on its website and marketing materials in accordance with its Privacy Policy.',
        ],
      },
      {
        heading: '8. Disclaimers and Limitation of Liability',
        body: [
          'PawnGold is provided on an "as is" and "as available" basis for academic and demonstration purposes. To the maximum extent permitted by law, we make no warranties regarding the platform\u2019s availability, accuracy, or fitness for a particular purpose.',
          'To the maximum extent permitted by law, PawnGold and its developers shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from your use of the platform.',
          'Because PawnGold is an academic project, no uptime, performance, or availability guarantees are provided and no service-level agreements are offered.',
        ],
      },
      {
        heading: '9. Termination',
        body: [
          'You may stop using PawnGold at any time. We may suspend or terminate access to the platform if you breach these Terms, if required by law, or if we discontinue the project.',
          'Upon termination, you should export any data you need. PawnGold may delete data in accordance with its data retention practices.',
        ],
      },
      {
        heading: '10. Changes to These Terms',
        body: [
          'We may update these Terms from time to time. When we make material changes, we will update the "Last updated" date at the top of this page. Continued use of the platform after changes take effect constitutes acceptance of the updated Terms.',
        ],
      },
      {
        heading: '11. Governing Law',
        body: [
          'These Terms are governed by the laws of the Republic of the Philippines. Any disputes shall be subject to the exclusive jurisdiction of the courts of Dasmarinas, Cavite, Philippines.',
        ],
      },
      {
        heading: '12. Contact',
        body: [
          'For questions about these Terms, you may contact the development team at the Dasmarinas, Cavite, Philippines academic institution that hosts this capstone project.',
        ],
      },
    ],
  },
  '/privacy': {
    metaTitle: 'Privacy Policy',
    updated: 'Last updated: September 10, 2026',
    intro:
      'This Privacy Policy explains how PawnGold collects, uses, stores, and protects personal data. It applies to the PawnGold platform, which is designed in accordance with the Philippine Data Privacy Act of 2012 (RA 10173).',
    sections: [
      {
        heading: '1. Information We Collect',
        body: [
          'Account information: name, email address, and password (stored securely) when you register a PawnGold account.',
          'Business information: the pawnshop name and business details you provide when setting up your organization.',
          'Operational data: the pawn tickets, customers, loans, inventory, staff, transactions, and documents you enter or upload into the platform while using it.',
          'Usage and device information: basic logs that help us operate and secure the service, such as IP address and timestamps of actions. We do not build advertising or behavior-tracking profiles.',
        ],
      },
      {
        heading: '2. How We Use Information',
        body: [
          'To provide, operate, and maintain the features of the platform, including loan management, receipts, contracts, and audit trails.',
          'To authenticate users and enforce role-based access controls.',
          'To process subscriptions and payments through our payment processor.',
          'To respond to support requests and, where you choose to submit a review, to display publicly approved reviews of registered owners.',
        ],
      },
      {
        heading: '3. Local Storage and Cookies',
        body: [
          'PawnGold does not use tracking or advertising cookies and does not embed third-party advertising or analytics trackers.',
          'To keep you signed in, we store session and authentication tokens in your browser\u2019s local storage. These tokens are essential for authentication and are not used for tracking.',
          'You can clear this data at any time through your browser settings. Clearing it will sign you out of the platform.',
        ],
      },
      {
        heading: '4. How We Share Information',
        body: [
          'We do not sell personal data.',
          'Information is shared only in limited circumstances: (a) with service providers who host the platform and process payments on our behalf under confidentiality obligations; (b) when required by Philippine law or lawful order; or (c) with your consent.',
          'Payment card details are handled exclusively by our payment processor (PayMongo) and are not stored on our servers.',
        ],
      },
      {
        heading: '5. Data Retention',
        body: [
          'Account and operational data are retained while your account is active and for a reasonable period afterward to comply with record-keeping expectations for regulated pawnshop operations.',
          'You are responsible for the records you must keep under applicable law. We encourage you to export your records periodically.',
        ],
      },
      {
        heading: '6. Your Rights Under the Data Privacy Act',
        body: [
          'As a data subject, you may exercise rights under RA 10173, including the right to be informed, the right to access, the right to object, the right to erasure or blocking, the right to rectify, and the right to data portability.',
          'To exercise these rights, contact the development team identified in the Terms of Service. We will respond within the period prescribed by law.',
          'You may also lodge a complaint with the National Privacy Commission of the Philippines if you believe your data protection rights have been violated.',
        ],
      },
      {
        heading: '7. Security',
        body: [
          'We implement reasonable technical and organizational safeguards, including encryption in transit, role-based access controls, and audit logging, to protect personal data.',
          'However, no method of transmission or storage is perfectly secure. You are responsible for protecting your login credentials and for the security of devices used to access the platform.',
        ],
      },
      {
        heading: '8. Data of Third Parties You Enter',
        body: [
          'When you enter customer, staff, or other third-party data into the platform, you act as a data controller for that data. You must have a lawful basis for processing it and respond to data subject requests made directly to you.',
          'PawnGold processes such data only to provide the services you request.',
        ],
      },
      {
        heading: '9. Children\u2019s Privacy',
        body: [
          'PawnGold is not directed to persons below the age of 18. We do not knowingly collect personal data from minors. If you believe a minor has provided personal data, contact us so we can remove it.',
        ],
      },
      {
        heading: '10. Changes to This Policy',
        body: [
          'We may update this Privacy Policy as the platform evolves. Material changes will be reflected by updating the "Last updated" date. Continued use of the platform constitutes acceptance of the updated policy.',
        ],
      },
    ],
  },
  '/cookies': {
    metaTitle: 'Cookie Policy',
    updated: 'Last updated: September 10, 2026',
    intro:
      'This Cookie Policy explains how PawnGold uses cookies and local storage. PawnGold is built for privacy: it does not use tracking cookies, advertising cookies, or third-party marketing pixels.',
    sections: [
      {
        heading: '1. Cookies',
        body: [
          'PawnGold does not place any cookies in your browser for analytics, advertising, or cross-site tracking.',
          'The only mechanism used to persist login state is your browser\u2019s local storage, which is not sent to third parties and is not used to build profiles about you.',
        ],
      },
      {
        heading: '2. Local Storage and Why We Use It',
        body: [
          'Local storage is used for a limited set of essential purposes:',
          '\u2022 Authentication tokens that keep you signed in across page loads.',
          '\u2022 Your last-viewed dashboard area and lightweight UI preferences, so the interface feels consistent.',
          '\u2022 Your cookie-notice preference, so we show the notice only until you acknowledge it once.',
        ],
      },
      {
        heading: '3. Third-Party Services',
        body: [
          'The platform may rely on service providers for hosting and payments (for example, our hosting provider and PayMongo). These providers have their own policies. Payment data is handled by the payment processor and is subject to its privacy and cookie practices.',
          'PawnGold itself does not operate third-party advertising or analytics trackers.',
        ],
      },
      {
        heading: '4. Managing Local Storage',
        body: [
          'You can clear local storage at any time through your browser\u2019s privacy or site-settings menu. Doing so may sign you out of the platform and reset lightweight preferences, but it will not delete data stored on our servers.',
          'After clearing local storage, the cookie notice banner will appear again on your next visit.',
        ],
      },
      {
        heading: '5. Contact',
        body: [
          'If you have questions about this Cookie Policy, contact the development team identified in the Terms of Service.',
        ],
      },
    ],
  },
  '/refunds': {
    metaTitle: 'Refund & Cancellation Policy',
    updated: 'Last updated: September 10, 2026',
    intro:
      'This policy explains how paid subscriptions, cancellations, and refunds work on the PawnGold platform. Because PawnGold is an academic capstone project, payment processing is provided for demonstration purposes only.',
    sections: [
      {
        heading: '1. Free Trial',
        body: [
          'New organizations may use PawnGold for a free trial period without charge and without providing payment details.',
          'You can cancel at any time during the trial without being charged.',
        ],
      },
      {
        heading: '2. Paid Plans and Billing',
        body: [
          'Paid plans are billed on a periodic basis (for example, monthly) through the payment processor (PayMongo). By subscribing, you authorize recurring charges at the published rate for your selected plan.',
          'Prices and plan features are published on the PawnGold website and may be updated with notice where reasonably practicable.',
        ],
      },
      {
        heading: '3. Cancellation',
        body: [
          'You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period, and you will retain access until that period ends.',
          'After cancellation, access to paid features is downgraded, but you may continue to export or retrieve your data during the notice period described in the Terms of Service.',
        ],
      },
      {
        heading: '4. Refunds',
        body: [
          'Because PawnGold is an academic demonstration project, refunds are generally not offered for partially used billing periods.',
          'If you believe you were charged in error or did not receive access to the service you paid for, contact the development team within 30 days of the charge. Refunds, where granted, will be issued to the original payment method.',
          'Refund eligibility is determined at our discretion and may be limited by the payment processor\u2019s rules.',
        ],
      },
      {
        heading: '5. Consumer Act Compliance',
        body: [
          'This policy is intended to align with the transparency requirements of the Consumer Act of the Philippines (RA 7394). Where a provision of Filipino consumer law grants you a non-waivable right, that right prevails over any conflicting term in this policy.',
        ],
      },
      {
        heading: '6. Contact',
        body: [
          'Billing, cancellation, and refund inquiries may be directed to the development team identified in the Terms of Service.',
        ],
      },
    ],
  },
};

export default function LegalDocPage({ path }: { path: string }) {
  const doc = DOCUMENTS[path] ?? DOCUMENTS['/terms'];

  return (
    <div className="min-h-screen" style={{ background: 'var(--bg-deep)', color: 'var(--text-primary)', fontFamily: 'var(--font-body)' }}>
      <div className="mx-auto max-w-3xl px-6 py-14 lg:px-8">
        <Link
          to="/"
          className="mb-8 inline-flex items-center gap-2 text-[13px] font-medium transition-opacity hover:opacity-80"
          style={{ color: 'var(--text-secondary)' }}
        >
          <ArrowLeft className="h-4 w-4" style={{ color: 'var(--gold)' }} />
          Back to home
        </Link>

        <div
          className="mb-4 inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-[11px] font-semibold tracking-[0.14em]"
          style={{ background: 'rgba(201,160,92,0.08)', border: '1px solid rgba(201,160,92,0.18)', color: 'var(--gold)' }}
        >
          <ShieldCheck className="h-3 w-3" />
          PAWNGOLD LEGAL
        </div>

        <h1 className="text-[34px] font-bold leading-tight tracking-tight sm:text-[44px]" style={{ fontFamily: 'var(--font-display)' }}>
          {doc.metaTitle}
        </h1>
        <p className="mt-2 text-[13px]" style={{ color: 'var(--text-muted)' }}>{doc.updated}</p>

        <p className="mt-8 rounded-[16px] p-5 text-[14px] leading-relaxed" style={{ background: 'rgba(201,160,92,0.05)', border: '1px solid rgba(201,160,92,0.15)', color: 'var(--text-secondary)' }}>
          {doc.intro}
        </p>

        <div className="mt-8 space-y-8">
          {doc.sections.map((section) => (
            <section key={section.heading}>
              <h2 className="text-[18px] font-bold tracking-tight" style={{ fontFamily: 'var(--font-display)', color: 'var(--gold)' }}>
                {section.heading}
              </h2>
              {section.body.map((paragraph, index) => (
                <p key={index} className="mt-2 text-[14px] leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
                  {paragraph}
                </p>
              ))}
            </section>
          ))}
        </div>

        <div
          className="mt-12 rounded-[16px] p-5"
          style={{ background: 'rgba(13,13,20,0.9)', border: '1px solid rgba(201,160,92,0.1)' }}
        >
          <p className="text-[12px] leading-relaxed" style={{ color: 'var(--text-dim)' }}>
            PawnGold is an academic thesis and capstone project developed in Dasmarinas, Cavite, Philippines.
            It is provided for demonstration and educational purposes only and is not a registered financial
            institution, money service business, or pawnshop operator.
          </p>
        </div>
      </div>
    </div>
  );
}