export const PERMISSIONS = {
  'platform.manage': 'platform.manage',
  'tenant.manage': 'tenant.manage',
  'tenant.view_audit': 'tenant.view_audit',
  'tenant.manage_branches': 'tenant.manage_branches',
  'user.manage_staff': 'user.manage_staff',
  'pawn_ticket.create': 'pawn_ticket.create',
  'pawn_ticket.view': 'pawn_ticket.view',
  'pawn_ticket.submit_approval': 'pawn_ticket.submit_approval',
  'pawn_ticket.approve': 'pawn_ticket.approve',
  'pawn_ticket.decline': 'pawn_ticket.decline',
  'pawn_ticket.appraise': 'pawn_ticket.appraise',
  'pawn_ticket.redeem': 'pawn_ticket.redeem',
  'pawn_ticket.send_to_auction': 'pawn_ticket.send_to_auction',
  'loan.create': 'loan.create',
  'loan.manage': 'loan.manage',
  'loan.collect': 'loan.collect',
  'auction.manage': 'auction.manage',
  'auction.settle': 'auction.settle',
  'auction.manual_settle': 'auction.manual_settle',
  'inventory.manage': 'inventory.manage',
  'compliance.view': 'compliance.view',
  'compliance.manage_documents': 'compliance.manage_documents',
  'onboarding.review_documents': 'onboarding.review_documents',
  'onboarding.approve': 'onboarding.approve',
  'reports.view': 'reports.view',
  'finance.manage': 'finance.manage',
  'approval.view_queue': 'approval.view_queue',
  'approval.approve_appraisal': 'approval.approve_appraisal',
  'approval.approve_redemption': 'approval.approve_redemption',
  'kyc.view': 'kyc.view',
  'kyc.verify': 'kyc.verify',
  'contract.sign': 'contract.sign',
  'contract.upload_signature': 'contract.upload_signature',
  'customer.view_history': 'customer.view_history',
  'customer.manage_tier': 'customer.manage_tier',
  'payroll.manage': 'payroll.manage',
  'attendance.manage': 'attendance.manage',
} as const;

export type PermissionName = keyof typeof PERMISSIONS;

export const ROLE_PERMISSIONS: Record<string, PermissionName[]> = {
  SUPER_ADMIN: ['platform.manage'],
  OWNER: [
    'tenant.manage',
    'tenant.view_audit',
    'tenant.manage_branches',
    'user.manage_staff',
    'pawn_ticket.create',
    'pawn_ticket.view',
    'pawn_ticket.submit_approval',
    'pawn_ticket.approve',
    'pawn_ticket.decline',
    'pawn_ticket.appraise',
    'pawn_ticket.redeem',
    'pawn_ticket.send_to_auction',
    'loan.create',
    'loan.manage',
    'loan.collect',
    'auction.manage',
    'auction.settle',
    'auction.manual_settle',
    'inventory.manage',
    'compliance.view',
    'compliance.manage_documents',
    'reports.view',
    'finance.manage',
    'approval.view_queue',
    'approval.approve_appraisal',
    'approval.approve_redemption',
    'kyc.view',
    'kyc.verify',
    'contract.sign',
    'contract.upload_signature',
    'customer.view_history',
    'customer.manage_tier',
    'payroll.manage',
    'attendance.manage',
  ],
  ADMIN: [
    'tenant.view_audit',
    'auction.settle',
    'auction.manual_settle',
    'approval.view_queue',
    'approval.approve_appraisal',
    'approval.approve_redemption',
    'kyc.view',
    'kyc.verify',
  ],
  MANAGER: [
    'tenant.manage_branches',
    'user.manage_staff',
    'pawn_ticket.create',
    'pawn_ticket.view',
    'pawn_ticket.submit_approval',
    'pawn_ticket.approve',
    'pawn_ticket.decline',
    'pawn_ticket.appraise',
    'pawn_ticket.redeem',
    'pawn_ticket.send_to_auction',
    'loan.create',
    'loan.manage',
    'loan.collect',
    'auction.settle',
    'inventory.manage',
    'reports.view',
    'finance.manage',
    'approval.view_queue',
    'contract.sign',
    'customer.manage_tier',
    'attendance.manage',
  ],
  HR: ['payroll.manage', 'attendance.manage'],
  STAFF: [
    'pawn_ticket.create',
    'pawn_ticket.view',
    'pawn_ticket.submit_approval',
    'loan.create',
    'compliance.view',
    'compliance.manage_documents',
    'contract.sign',
    'customer.view_history',
  ],
  CASHIER_TELLER: [
    'pawn_ticket.create',
    'pawn_ticket.view',
    'pawn_ticket.submit_approval',
    'pawn_ticket.redeem',
    'loan.create',
    'loan.collect',
    'compliance.view',
    'compliance.manage_documents',
    'contract.sign',
    'customer.view_history',
    'approval.view_queue',
  ],
  APPRAISER: [
    'pawn_ticket.create',
    'pawn_ticket.view',
    'pawn_ticket.submit_approval',
    'pawn_ticket.appraise',
    'loan.create',
    'compliance.view',
    'compliance.manage_documents',
    'contract.sign',
    'customer.view_history',
    'approval.view_queue',
  ],
  INVENTORY_CUSTODIAN: ['pawn_ticket.view', 'inventory.manage'],
  AUDITOR: ['pawn_ticket.view', 'reports.view', 'tenant.view_audit', 'finance.manage'],
};
